language: haskell
cabal: "3.4" # Temporary pin until a sufficiently recent version is in the standard Travis images
addons:
  apt:
    packages:
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - freeglut3-dev
      - libpulse-dev
      - libblas-dev
      - liblapack-dev
      - libasound2-dev
    sources:
      - sourceline: 'ppa:hvr/ghc'
cache:
  directories:
    - $HOME/.cabal
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/.stack-work

matrix:
  include:

  # Cabal
  - ghc: '8.10'
  - ghc: '8.8'
  - ghc: '8.6'

  # Stack
  - ghc: '8.10.4'
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"
  - ghc: '8.8.4'
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack-lts-16.31.yaml"
  - ghc: '8.6.5'
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack-lts-14.27.yaml"

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal new-build all --enable-tests
      cabal new-test all --enable-tests
      # git fetch origin master:origin/master && git rebase origin/master --exec "cabal new-build all --enable-tests"
    else
      # install stack
      curl -sSL https://get.haskellstack.org/ | sh

      # build project with stack
      stack --version
      stack build --system-ghc --test
      # git fetch origin master:origin/master && git rebase origin/master --exec "stack build --system-ghc --test"
    fi

install: skip
